/*!
    \file main.cpp
    \brief Problem #2. Even Fibonacci numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main()
{
    int x = 1;
    int y = 1;

    unsigned int sum = 0;

    while(1) {
        int nextFibElem = x + y;
        x = y;
        y = nextFibElem;

        if (nextFibElem >= 4000000) {
            break;
        }

        if ( !(nextFibElem & 1) ) {
            sum += nextFibElem;
        }
    }

    cout << sum << endl;

    return 0;
}

